blank_issues_enabled: false
contact_links:
  - name: Contributing Guide
    url: https://github.com/gguip1/SoundBadge/blob/main/CONTRIBUTING.md
    about: Please read the contributing guide before opening an issue.
